travis:
  secure:
    BINSTAR_TOKEN: rSymXsmhQQvnCf53wpqM1JKBdgyTG+HmhGbXcmX7tlbH9pUkYVbTP0iGAj+Kq45KN9selXBhS2m0O5eV0wxTSm2go8XhrHLhN/wxXSgUFpDiVVd/Yn1fm+ncRvlfyiXvK6y8Nu9ne/seRrQ7D+IzY1cQ81V6YQk1o/PnesvAPlBv8oXa97//2Lc97OGn2peGmAxuE4bkeAgBMJSCTQdT8WMBz+9+ny2TlCn3BF0CoHG3AIdxWGtHOoFkx+FbMbPhRORb28Uetu529jRFrK0IPbMJkdGfQpntjC0p4kIsuJPCs/P+e2401OKaXlfO+BF246WDqs6azSs9rAyRecQVoxUNop9WlQvZUPdkhjZJ4fURTqihbHM5MB3QFQNWmuZ1JT4vBkQgTa0flEUsrBkMpTZ+3EY3dui9wLCadkOS/2cEZxpWfhdiRdPLUmUYUWRacwA4jIcUc2Nsu6D/ELQVDhiXBP7vsSphXjgJc+2ZjUs9lu4ReKXEsVOYgIIYYR+QYvYdTO389RjUnyFKK9hbo1zUg/+Z+2J7azO7dwfgP9Ss2PcM1zTEN5OkqY5HGL9RL8Tlzes+YXVm/gcAknaakflQ+7YQa1u0/sGINB7W/GL4T/A62mXIZbRA23P/9swz/anHY/QcG5o3rikjMDI92EX/Np+jKzxrstScIrdvSR4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
