travis:
  secure:
    BINSTAR_TOKEN: G8pWHkmAllhbvk9afkFBmmXaP+rNcnF3kuRx0LANlHSZrGscTItq3WckGt1Bn59nW1DmC2S3v5huhrAhWd5msAAFRCKhQGqanAf1o4fjlbES40ZIhO5mYEwqPzUbkLmYeHhzlJ1ncfkth3crTlFMOJz2FqzdKagJ2lgjJIo/mxaHCIXNJ3eP7sZ2XoceTKVodGYoP6JezDzGEf30DLLZEh859/YOwAOhHc9yq+mYj2hrJo70LKldnYwtTjFriayt0hcON/sHH7SrTIS4MWHYuufdtvThov293UvAJtsSJfkEqDS8HEpj8vP/97ULwqnlRnJNdBz3eLX4Tl34c/mhY8Lh9U7LJ9RPYQx2vy9W1ZnW1ArfHxPLbjttk1vQEefj8eCsO7bvSr2wgrrvntt0OWA4b3iXLn21FI8WD0na7khXutdic5qBJkZKoLdDJbGkHDA7aM5TlDLFzn/DTEcdJ3s3WmT4x15u1WQg+RAjlfkszQ3Y90eQvm/c//m9gMU6hzXGPwpZU9aqu0WWviwGyuvAsDf6EQT4uL9FIEjSr9fCPbCChcxgGvAGMiJcwKkOB4YtHeCyD510NDpI4/FJZ4zZ8G7Dt6ON7tBJ8YZyXRVynwzz/qIV1zpXjDK54rIs8rYO2MIg4OM6ghwWVt+wXfg94qKGNTsNdL2WphAoomQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
